import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  TopHeader from "@/components/TopHeader/TopHeader";
import Footer from "@/components/Footer/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopHeader></TopHeader>
        <div className="flex flex-col items-center justify-center mt-[88px] tablet:mt-[72px] mobile:mt-24">
          {children}
        </div>
        <Footer />
        
      </body>
    </html>
  );
}
